### ISSUE TITLE
Exception on app launch on Windows

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#106]
On Windows 7 with the last develop branch:
```
pip install alignak_app -v --user
```

I got: 
```
C:\Users\mohierf\AppData\Roaming\Python\alignak_app>python bin\alignak-app.py
Traceback (most recent call last):
  File "C:\Users\mohierf\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 786, in get
    value = d[option]
  File "C:\Users\mohierf\AppData\Local\Programs\Python\Python35\lib\collections\__init__.py", line 878, in __
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\mohierf\AppData\Local\Programs\Python\Python35\lib\collections\__init__.py", line 870, in __
    raise KeyError(key)
KeyError: 'alignak_backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\github\alignak-app\alignak_app\core\utils.py", line 153, in get_app_config
    return app_config.get(section, option)
  File "C:\Users\mohierf\AppData\Local\Programs\Python\Python35\lib\configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'alignak_backend' in section: 'Backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin\alignak-app.py", line 51, in <module>
    alignak_app.start()
  File "d:\github\alignak-app\alignak_app\app.py", line 75, in start
    if get_app_config('Backend', 'alignak_backend'):
  File "d:\github\alignak-app\alignak_app\core\utils.py", line 156, in get_app_config
    logger.error('Replace by : ' + option + ': ' + str(default_parameters[option]))
KeyError: 'alignak_backend'
```

**Comment by mohierf** [comment]
Promised! I stop trying with old versions ... instead I run the Windows installer :wink:
