### ISSUE TITLE
Catch backend exceptions ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-app#13]
You should catch the backend exception ... when losing connection to the backend because of a restart, I got this message in the shell from where I started the app:

```
Traceback (most recent call last):
  File "/home/alignak/alignak-app/alignak_app/application.py", line 229, in notify_change
    hosts_states, services_states = self.get_state()
  File "/home/alignak/alignak-app/alignak_app/application.py", line 204, in get_state
    hosts_data = self.backend_data.get_host_state()
  File "/home/alignak/alignak-app/alignak_app/alignak_data.py", line 53, in get_host_state
    '/livestate?where={"type":"host"}')
  File "/home/alignak/alignak-webui/src/alignak-backend-client/alignak_backend_client/client.py", line 370, in get_all
    resp = self.get(endpoint, params)
  File "/home/alignak/alignak-webui/src/alignak-backend-client/alignak_backend_client/client.py", line 299, in get
    auth=HTTPBasicAuth(self.token, '')
  File "/home/alignak/.local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/alignak/.local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alignak/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alignak/.local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/alignak/.local/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /livestate?where=%7B%22type%22:%22host%22%7D&max_results=50 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f1a680cf150>: Failed to establish a new connection: [Errno 111] Connection refused',))

```

**Comment by algorys** [comment]
Normally exceptions are now catch. Tell me if problem persist.
