### ISSUE TITLE
crash when enter new server address

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring-contrib/alignak-app#177]
when I enter new server url and validate it, it crash and I have this error:

```
Traceback (most recent call last):
  File "/home/ddurieux/.local/lib/python2.7/site-packages/alignak_app/widgets/login.py", line 280, in handle_server
    set_app_config('Alignak', 'backend', backend_url)
  File "/home/ddurieux/.local/lib/python2.7/site-packages/alignak_app/core/utils.py", line 188, in set_app_config
    for d in data:
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by algorys** [comment]
Fixed by 	c89e1da. BSD was not manage for `set_app_config`
