### ISSUE TITLE
"No section: 'Log'" on Windows post upgrade  with "..\pip install . --user --upgrade"

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-app#189]
```
C:\Users\%USERNAME%>C:\Python34\python.exe c:\Users\%USERNAME%\AppData\Roaming\Python\alignak_app\bin\alignak-app.py

Traceback (most recent call last):
  File "C:\Python34\lib\configparser.py", line 1116, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\%USERNAME%\AppData\Roaming\Python\alignak_app\bin\alignak-app.py", line 29, in <module>
    from alignak_app.app import AlignakApp
  File "C:\Users\%USERNAME%\AppData\Roaming\Python\Python34\site-packages\alignak_app\app.py", line 51, in <module>
    logger = create_logger()
  File "C:\Users\%USERNAME%\AppData\Roaming\Python\Python34\site-packages\alignak_app\core\logs.py", line 52, in create_logger
    if get_app_config('Log', 'location'):
  File "C:\Users\%USERNAME%\AppData\Roaming\Python\Python34\site-packages\alignak_app\core\utils.py", line 151, in get_app_config
    return app_config.get(section, option)
  File "C:\Python34\lib\configparser.py", line 754, in get
    d = self._unify_values(section, vars)
  File "C:\Python34\lib\configparser.py", line 1119, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Log'
```

**Comment by algorys** [comment]
@spea1 it seems it's due to #186 . 

In fact, I was thinking that Windows users will only use the setup to install App. More easy to install / update / maintain and avoid to keep a `cmd` open.

So now, App search for files in `C:\Program Files\Alignak-app` only. That's why you have this error... App can't find your `settings.cfg` file !

Before, App search on many location under Windows which led to a complication of the code, that's why I delete this part.

I think future users will use Setup in future on Windows. (Linux install has no change because more perfect :wink: )

@mohierf @ddurieux what do you think of that ?

**Comment by spea1** [comment]
It works as well
:: run as admin
:: Do not use var  %USERNAME% for *U*S*E*R*N*A*M*E*
```
mklink /J "%ProgramFiles%\Alignak-app" c:\Users\*U*S*E*R*N*A*M*E*\AppData\Roaming\Python\alignak_app
```

**Comment by algorys** [comment]
Nice idea, I forget this command :yum: . I've added in the doc. Thanks @spea1

**Comment by algorys** [comment]
Catch all errors anyway for `settings.cfg`

**Comment by algorys** [comment]
Better like that.

- Log messages improved 
- Exit messages improved 
- App stop if she encounter too much errors at start
- Fix some cases where BSD was not managed
