### ISSUE TITLE
json.decoder.JSONDecodeError: Unterminated string starting at:

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-app#209]
When app enter in **reconnect mode**, when trying to reconnect, `alignak-backend-client` trigger following error:

```python
/usr/bin/python3.5 /home/algorys/workspace/personnal-repos/alignak-app/bin/unix/alignak-app.py
WARNING:alignak_app.core.locales:Locale not found. Using default language messages (English)
371
Traceback (most recent call last):
  File "/home/algorys/workspace/personnal-repos/alignak-app/alignak_app/threads/backend_thread.py", line 59, in run
    app_backend.query_services_data()
  File "/home/algorys/workspace/personnal-repos/alignak-app/alignak_app/core/backend.py", line 432, in query_services_data
    all_items=True
  File "/home/algorys/workspace/personnal-repos/alignak-app/alignak_app/core/backend.py", line 160, in get
    params
  File "/home/algorys/.local/lib/python3.5/site-packages/alignak_backend_client/client.py", line 402, in get_all
    resp = self.get(endpoint, params)
  File "/home/algorys/.local/lib/python3.5/site-packages/alignak_backend_client/client.py", line 341, in get
    resp = response.json()
  File "/home/algorys/.local/lib/python3.5/site-packages/requests/models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 33121 (char 33120)
QThread: Destroyed while thread is still running
```

Certainly due to missing data between client and server. App should catch this exception.

Thread is destroyed after as expected.

@ddurieux and @mohierf , FYI :wink:

**Comment by algorys** [comment]
Exception is now catched.
